import Link from "next/link";

export const metadata = { title: "Terms of Service — Real or Fake News" };

const LAST_UPDATED = "April 14, 2026";

export default function TermsPage() {
  return (
    <main className="mx-auto min-h-dvh w-full max-w-2xl px-6 py-16">
      <Link
        href="/"
        className="text-xs font-bold uppercase tracking-[0.3em] text-neutral-500 hover:text-amber-400"
      >
        ← Back to game
      </Link>

      <header className="mt-6">
        <p className="text-xs font-bold uppercase tracking-[0.3em] text-amber-400">
          Real or Fake News
        </p>
        <h1 className="mt-2 text-4xl font-black">Terms of Service &amp; Privacy Policy</h1>
        <p className="mt-2 text-sm text-neutral-500">Last updated: {LAST_UPDATED}</p>
      </header>

      <div className="prose prose-invert mt-10 max-w-none space-y-8 text-neutral-300">
        <section>
          <h2 className="text-xl font-black text-white">1. Entertainment Only — Not News</h2>
          <p>
            Real or Fake News is a guessing game. Some of the headlines shown in the game are
            genuine excerpts from real news sources, and some are entirely fabricated by an AI
            language model for the purposes of the game. You agree that:
          </p>
          <ul className="list-disc space-y-2 pl-6">
            <li>
              The game is for <strong>entertainment purposes only</strong>. No headline shown
              in the game should be treated as a reliable source of information, even the real
              ones.
            </li>
            <li>
              You will <strong>not share, screenshot, quote, or republish</strong> any headline
              from the game as if it were news. The fake headlines are designed to be
              plausible and could mislead others if taken out of the game's context.
            </li>
            <li>
              Real or Fake News and its operators are not responsible for any harm caused by a
              user sharing game content outside of the game.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-black text-white">2. No Commercial Use</h2>
          <p>
            You may not use, scrape, redistribute, rehost, mirror, repackage, resell, or
            incorporate any content from Real or Fake News into any commercial product or service.
            This includes, without limitation, the game's headlines (real or fake), reveal
            text, game mechanics, UI, leaderboard data, and generated content. Personal,
            non-commercial play is permitted and encouraged.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-black text-white">3. Accounts &amp; Display Names</h2>
          <p>
            You may sign in using a magic-link email. You are responsible for the email address
            and display name you choose. You agree not to impersonate any person or entity,
            use offensive or abusive language, or choose a name that infringes on someone
            else's rights. We may remove or reassign any display name at our discretion.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-black text-white">4. Third-Party Content &amp; Sources</h2>
          <p>
            Real headlines may be sourced from third-party news providers, aggregators, and
            APIs. Real or Fake News is not affiliated with, endorsed by, or sponsored by any news
            outlet. All trademarks and source names remain the property of their respective
            owners. Real headlines are used in an excerpted form for the limited, transformative
            purpose of a guessing game.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-black text-white">5. AI-Generated Content</h2>
          <p>
            Fake headlines are generated by a large language model. Despite content guardrails
            in the generation process, the model may occasionally produce output that is
            inaccurate, insensitive, or unintentionally similar to real events. If you
            encounter content that should be reviewed or removed, please contact us.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-black text-white">6. Privacy Policy</h2>
          <p>
            <strong>What we collect.</strong> When you sign in, we collect your email address
            (used only to authenticate you via a magic link) and the display name you choose.
            When you play a game, we collect your final score, best streak, and a timestamp.
            We do not collect your name, address, phone number, location, payment information,
            or any other personal data.
          </p>
          <p>
            <strong>How we use it.</strong> Your email is used only to send you sign-in links.
            Your display name, scores, and streaks appear on public leaderboards. We do not
            sell, rent, or share your information with third parties for marketing.
          </p>
          <p>
            <strong>Where it lives.</strong> Authentication and data storage are provided by
            Supabase. Your session is maintained via a secure HTTP cookie. We use no tracking,
            advertising, or analytics cookies.
          </p>
          <p>
            <strong>How long we keep it.</strong> We keep your account and scores until you
            ask us to delete them. A self-service data deletion flow is coming soon. Until
            then, contact us and we will delete your account, profile, and all associated
            scores within a reasonable period.
          </p>
          <p>
            <strong>Children.</strong> Real or Fake News is not directed at children under 13 and
            we do not knowingly collect data from anyone under 13.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-black text-white">7. Disclaimers</h2>
          <p>
            The game is provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo;
            basis, without warranties of any kind, express or implied. We do not warrant that
            the game will be uninterrupted, error-free, or free of harmful content. To the
            fullest extent permitted by law, Real or Fake News and its operators disclaim all
            liability for any direct, indirect, incidental, consequential, or punitive
            damages arising from your use of the game.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-black text-white">8. Changes</h2>
          <p>
            We may update these Terms from time to time. Material changes will be communicated
            on the home screen or via the acknowledgement checkbox. Your continued use of the
            game after an update constitutes acceptance of the updated Terms.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-black text-white">9. Contact</h2>
          <p>
            Questions, content concerns, or account deletion requests:{" "}
            <a
              href="mailto:support@real-or-fake.app"
              className="text-amber-400 underline underline-offset-4"
            >
              support@real-or-fake.app
            </a>
            .
          </p>
        </section>
      </div>
    </main>
  );
}
